/**
 * CPR DPP Tracker — Admin Panel
 *
 * Reads review-queue.json (generated by CPR Expert agent via Claude Code).
 * Presents data updates for human approval/rejection.
 * On "Apply Approved", writes changes directly to families.json via File System Access API.
 *
 * No third-party services. All local.
 */

(function () {
  'use strict';

  // ─── Constants ───
  var ADMIN_HASH = '5e884898da28047151d0e56f8dc6292773603d0d6aabbdd62a11ef721d1542d8'; // sha256 of 'password' — change in production
  var LS_AUTH_KEY = 'cpr-admin-auth';
  var LS_CHAT_KEY = 'cpr-admin-chat';
  var LS_QUEUE_KEY = 'cpr-admin-queue';

  // ─── State ───
  var queue = null;           // The loaded review-queue.json data
  var familiesData = null;    // The loaded families.json data
  var familiesHandle = null;  // File System Access API handle for families.json
  var queueHandle = null;     // File System Access API handle for review-queue.json

  // ─── DOM refs ───
  var authGate = document.getElementById('authGate');
  var authInput = document.getElementById('authInput');
  var authBtn = document.getElementById('authBtn');
  var authError = document.getElementById('authError');
  var adminContent = document.getElementById('adminContent');

  var statPending = document.getElementById('statPending');
  var statApproved = document.getElementById('statApproved');
  var statRejected = document.getElementById('statRejected');
  var statIssues = document.getElementById('statIssues');

  var queueMeta = document.getElementById('queueMeta');
  var queueSource = document.getElementById('queueSource');
  var queueDate = document.getElementById('queueDate');
  var queueFamilies = document.getElementById('queueFamilies');
  var noQueueActions = document.getElementById('noQueueActions');
  var adminTabs = document.getElementById('adminTabs');

  var updatesList = document.getElementById('updatesList');
  var issuesList = document.getElementById('issuesList');

  var loadQueueBtn = document.getElementById('loadQueueBtn');
  var loadQueueBtnEmpty = document.getElementById('loadQueueBtnEmpty');
  var applyApprovedBtn = document.getElementById('applyApprovedBtn');
  var clearQueueBtn = document.getElementById('clearQueueBtn');

  var chatMessages = document.getElementById('chatMessages');
  var chatInput = document.getElementById('chatInput');
  var chatSendBtn = document.getElementById('chatSendBtn');

  // ─── Auth ───
  function sha256(str) {
    var encoder = new TextEncoder();
    var data = encoder.encode(str);
    return crypto.subtle.digest('SHA-256', data).then(function (buf) {
      return Array.from(new Uint8Array(buf)).map(function (b) {
        return b.toString(16).padStart(2, '0');
      }).join('');
    });
  }

  function checkAuth() {
    var stored = localStorage.getItem(LS_AUTH_KEY);
    if (stored === 'true') {
      showAdmin();
    }
  }

  function authenticate() {
    var val = authInput.value.trim();
    if (!val) return;
    sha256(val).then(function (hash) {
      if (hash === ADMIN_HASH) {
        localStorage.setItem(LS_AUTH_KEY, 'true');
        authError.style.display = 'none';
        showAdmin();
      } else {
        authError.style.display = 'block';
        authInput.value = '';
        authInput.focus();
      }
    });
  }

  function showAdmin() {
    authGate.style.display = 'none';
    adminContent.style.display = 'block';
    loadSavedQueue();
    loadChat();
  }

  // ─── Queue Loading ───
  function loadQueueFromFile() {
    if (!window.showOpenFilePicker) {
      // Fallback for browsers without File System Access API
      var input = document.createElement('input');
      input.type = 'file';
      input.accept = '.json';
      input.onchange = function () {
        if (input.files.length === 0) return;
        var reader = new FileReader();
        reader.onload = function () {
          try {
            var data = JSON.parse(reader.result);
            setQueue(data);
          } catch (e) {
            alert('Invalid JSON file: ' + e.message);
          }
        };
        reader.readAsText(input.files[0]);
      };
      input.click();
      return;
    }

    window.showOpenFilePicker({
      types: [{ description: 'JSON files', accept: { 'application/json': ['.json'] } }],
      multiple: false
    }).then(function (handles) {
      queueHandle = handles[0];
      return queueHandle.getFile();
    }).then(function (file) {
      return file.text();
    }).then(function (text) {
      var data = JSON.parse(text);
      setQueue(data);
    }).catch(function (e) {
      if (e.name !== 'AbortError') {
        console.error('Failed to load queue:', e);
      }
    });
  }

  function setQueue(data) {
    queue = data;
    // Ensure all items have a status
    if (queue.dataUpdates) {
      queue.dataUpdates.forEach(function (u) {
        if (!u.status) u.status = 'pending';
      });
    }
    if (queue.structuralIssues) {
      queue.structuralIssues.forEach(function (i) {
        if (!i.status) i.status = 'pending';
      });
    }
    saveQueue();
    renderQueue();
  }

  function saveQueue() {
    if (queue) {
      localStorage.setItem(LS_QUEUE_KEY, JSON.stringify(queue));
    } else {
      localStorage.removeItem(LS_QUEUE_KEY);
    }
  }

  function loadSavedQueue() {
    var saved = localStorage.getItem(LS_QUEUE_KEY);
    if (saved) {
      try {
        queue = JSON.parse(saved);
        renderQueue();
      } catch (e) {
        // Corrupted — clear
        localStorage.removeItem(LS_QUEUE_KEY);
      }
    }
  }

  // ─── Queue Rendering ───
  function renderQueue() {
    if (!queue) {
      noQueueActions.style.display = 'flex';
      queueMeta.style.display = 'none';
      adminTabs.style.display = 'none';
      updatesList.innerHTML = '';
      issuesList.innerHTML = '';
      renderEmpty(updatesList, 'No queue loaded', 'Use the CPR Expert agent to run /scan or /dive, then /review to generate a review-queue.json file.');
      updateStats(0, 0, 0, 0);
      return;
    }

    noQueueActions.style.display = 'none';
    queueMeta.style.display = 'flex';
    adminTabs.style.display = 'flex';

    // Meta
    if (queue.meta) {
      queueSource.textContent = queue.meta.source || '—';
      queueDate.textContent = queue.meta.generated ? new Date(queue.meta.generated).toLocaleString() : '—';
      queueFamilies.textContent = (queue.meta.families_affected || []).join(', ') || '—';
    }

    var updates = queue.dataUpdates || [];
    var issues = queue.structuralIssues || [];

    // Counts
    var pending = updates.filter(function (u) { return u.status === 'pending'; }).length;
    var approved = updates.filter(function (u) { return u.status === 'approved'; }).length;
    var rejected = updates.filter(function (u) { return u.status === 'rejected' || u.status === 'dismissed'; }).length;
    var openIssues = issues.filter(function (i) { return i.status === 'pending'; }).length;
    updateStats(pending, approved, rejected, openIssues);

    // Tab counts
    document.getElementById('tabUpdatesCount').textContent = updates.length;
    document.getElementById('tabIssuesCount').textContent = issues.length;

    // Enable/disable apply button
    applyApprovedBtn.disabled = approved === 0;

    // Render updates
    updatesList.innerHTML = '';
    if (updates.length === 0) {
      renderEmpty(updatesList, 'No data updates', 'The review queue contains no data updates.');
    } else {
      updates.forEach(function (update, index) {
        updatesList.appendChild(createUpdateCard(update, index));
      });
    }

    // Render issues
    issuesList.innerHTML = '';
    if (issues.length === 0) {
      renderEmpty(issuesList, 'No structural issues', 'No structural issues were flagged by the agent.');
    } else {
      issues.forEach(function (issue, index) {
        issuesList.appendChild(createIssueCard(issue, index));
      });
    }
  }

  function updateStats(pending, approved, rejected, issues) {
    statPending.textContent = pending;
    statApproved.textContent = approved;
    statRejected.textContent = rejected;
    statIssues.textContent = issues;
  }

  function renderEmpty(container, title, text) {
    container.innerHTML =
      '<div class="admin-empty">' +
        '<span class="admin-empty__icon" aria-hidden="true">&#128230;</span>' +
        '<div class="admin-empty__title">' + escapeHtml(title) + '</div>' +
        '<p class="admin-empty__text">' + escapeHtml(text) + '</p>' +
      '</div>';
  }

  function isNoOp(update) {
    var action = update.action || 'set';
    if (action !== 'set') return false;
    return JSON.stringify(update.current_value) === JSON.stringify(update.proposed_value);
  }

  function createUpdateCard(update, index) {
    var card = document.createElement('div');
    var noop = isNoOp(update);
    card.className = 'update-card';
    if (update.status === 'approved') card.className += ' update-card--approved';
    if (update.status === 'rejected') card.className += ' update-card--rejected';
    if (noop) card.className += ' update-card--noop';

    var confidenceClass = 'update-card__badge--' + (update.confidence || 'medium');

    var html =
      '<div class="update-card__header">' +
        '<span class="update-card__family">' + escapeHtml(update.family || '?') + '</span>' +
        (noop ? '<span class="update-card__badge update-card__badge--info">confirmation</span>' : '') +
        '<span class="update-card__badge ' + confidenceClass + '">' + escapeHtml(update.confidence || 'medium') + '</span>' +
      '</div>' +
      '<div class="update-card__field">' +
        (update.action === 'update_standard' ? 'Update standard: <strong>' + escapeHtml(update.standard_id || '?') + '</strong>' :
         update.action === 'add_standard' ? 'Add standard: <strong>' + escapeHtml((update.proposed_value && update.proposed_value.id) || update.standard_id || '?') + '</strong> to ' + escapeHtml(update.family) :
         update.action === 'remove_standard' ? 'Remove standard: <strong>' + escapeHtml(update.standard_id || '?') + '</strong> from ' + escapeHtml(update.family) :
         'Field: <strong>' + escapeHtml(update.field || '?') + '</strong>') +
      '</div>';

    if (noop) {
      html +=
        '<div class="update-card__diff update-card__diff--noop">' +
          '<span class="update-card__new" style="border-color:rgba(59,130,246,0.15);color:#3B82F6;background:rgba(59,130,246,0.06);">' + escapeHtml(formatValue(update.current_value)) + '</span>' +
          '<span style="font-size:0.72rem;color:var(--text-secondary);margin-left:4px;">verified, no change</span>' +
        '</div>';
    } else {
      html +=
        '<div class="update-card__diff">' +
          '<span class="update-card__old">' + escapeHtml(formatValue(update.current_value)) + '</span>' +
          '<span class="update-card__arrow">&rarr;</span>' +
          '<span class="update-card__new">' + escapeHtml(formatValue(update.proposed_value)) + '</span>' +
        '</div>';
    }

    html += '<div class="update-card__reason">' + escapeHtml(update.reason || '') + '</div>';

    if (update.source) {
      html += '<div class="update-card__source">Source: ';
      if (update.source_url) {
        html += '<a href="' + escapeHtml(update.source_url) + '" target="_blank" rel="noopener">' + escapeHtml(update.source) + '</a>';
      } else {
        html += escapeHtml(update.source);
      }
      html += '</div>';
    }

    if (update.status === 'pending') {
      if (noop) {
        html +=
          '<div class="update-card__actions">' +
            '<button class="btn btn--sm btn--outline" data-action="dismiss" data-index="' + index + '">Dismiss</button>' +
          '</div>';
      } else {
        html +=
          '<div class="update-card__actions">' +
            '<button class="btn btn--sm btn--primary" data-action="approve" data-index="' + index + '">Approve</button>' +
            '<button class="btn btn--sm btn--danger" data-action="reject" data-index="' + index + '">Reject</button>' +
          '</div>';
      }
    } else {
      var statusLabel = update.status === 'approved' ? 'Approved' :
                        update.status === 'dismissed' ? 'Dismissed' : 'Rejected';
      html +=
        '<div class="update-card__actions">' +
          '<span class="update-card__status update-card__status--' + update.status + '">' + statusLabel + '</span>' +
          '<button class="btn btn--xs btn--outline" data-action="reset" data-index="' + index + '" style="margin-left:auto;">Reset</button>' +
        '</div>';
    }

    card.innerHTML = html;

    // Event delegation for buttons
    card.addEventListener('click', function (e) {
      var btn = e.target.closest('[data-action]');
      if (!btn) return;
      var action = btn.getAttribute('data-action');
      var idx = parseInt(btn.getAttribute('data-index'), 10);
      handleUpdateAction(action, idx);
    });

    return card;
  }

  function createIssueCard(issue, index) {
    var card = document.createElement('div');
    card.className = 'issue-card issue-card--' + (issue.severity || 'info');
    if (issue.status === 'acknowledged') card.className += ' issue-card--acknowledged';
    if (issue.status === 'resolved') card.className += ' issue-card--resolved';

    var html =
      '<div class="issue-card__header">' +
        '<span class="issue-card__title">' + escapeHtml(issue.title || 'Untitled') + '</span>' +
        '<span class="update-card__badge update-card__badge--' + (issue.severity || 'info') + '">' + escapeHtml(issue.severity || 'info') + '</span>' +
      '</div>';

    if (issue.families && issue.families.length > 0) {
      html += '<div class="issue-card__families">';
      issue.families.forEach(function (f) {
        html += '<span class="issue-card__family-tag">' + escapeHtml(f) + '</span>';
      });
      html += '</div>';
    }

    html += '<div class="issue-card__description">' + escapeHtml(issue.description || '') + '</div>';

    if (issue.action_required) {
      html += '<div class="issue-card__action">Action: ' + escapeHtml(issue.action_required) + '</div>';
    }

    if (issue.source) {
      html += '<div class="update-card__source">Source: ';
      if (issue.source_url) {
        html += '<a href="' + escapeHtml(issue.source_url) + '" target="_blank" rel="noopener">' + escapeHtml(issue.source) + '</a>';
      } else {
        html += escapeHtml(issue.source);
      }
      html += '</div>';
    }

    // Issue status actions
    if (issue.status === 'pending') {
      html +=
        '<div class="update-card__actions" style="margin-top:10px;">' +
          '<button class="btn btn--xs btn--teal" data-issue-action="acknowledge" data-issue-index="' + index + '">Acknowledge</button>' +
          '<button class="btn btn--xs btn--outline" data-issue-action="resolve" data-issue-index="' + index + '">Resolve</button>' +
        '</div>';
    } else {
      var label = issue.status === 'acknowledged' ? 'Acknowledged' : 'Resolved';
      html +=
        '<div class="update-card__actions" style="margin-top:10px;">' +
          '<span class="update-card__status update-card__status--' + (issue.status === 'resolved' ? 'approved' : 'dismissed') + '">' + label + '</span>' +
          '<button class="btn btn--xs btn--outline" data-issue-action="reopen" data-issue-index="' + index + '" style="margin-left:auto;">Reopen</button>' +
        '</div>';
    }

    card.innerHTML = html;

    card.addEventListener('click', function (e) {
      var btn = e.target.closest('[data-issue-action]');
      if (!btn) return;
      var action = btn.getAttribute('data-issue-action');
      var idx = parseInt(btn.getAttribute('data-issue-index'), 10);
      handleIssueAction(action, idx);
    });

    return card;
  }

  function handleIssueAction(action, index) {
    if (!queue || !queue.structuralIssues || !queue.structuralIssues[index]) return;
    if (action === 'acknowledge') {
      queue.structuralIssues[index].status = 'acknowledged';
    } else if (action === 'resolve') {
      queue.structuralIssues[index].status = 'resolved';
    } else if (action === 'reopen') {
      queue.structuralIssues[index].status = 'pending';
    }
    saveQueue();
    renderQueue();
  }

  // ─── Update Actions ───
  function handleUpdateAction(action, index) {
    if (!queue || !queue.dataUpdates || !queue.dataUpdates[index]) return;

    if (action === 'approve') {
      queue.dataUpdates[index].status = 'approved';
    } else if (action === 'reject') {
      queue.dataUpdates[index].status = 'rejected';
    } else if (action === 'dismiss') {
      queue.dataUpdates[index].status = 'dismissed';
    } else if (action === 'reset') {
      queue.dataUpdates[index].status = 'pending';
    }

    saveQueue();
    renderQueue();
  }

  // ─── Apply Approved Changes ───
  function applyApproved() {
    if (!queue || !queue.dataUpdates) return;

    var approved = queue.dataUpdates.filter(function (u) { return u.status === 'approved'; });
    if (approved.length === 0) {
      alert('No approved changes to apply.');
      return;
    }

    // If we have File System Access API, use it for direct file writing
    if (window.showOpenFilePicker) {
      applyWithFileSystemAccess(approved);
    } else {
      applyWithDownload(approved);
    }
  }

  function applyWithFileSystemAccess(approved) {
    // Step 1: User picks families.json
    var pickerOpts = {
      types: [{ description: 'JSON files', accept: { 'application/json': ['.json'] } }],
      multiple: false
    };

    window.showOpenFilePicker(pickerOpts).then(function (handles) {
      familiesHandle = handles[0];
      return familiesHandle.getFile();
    }).then(function (file) {
      return file.text();
    }).then(function (text) {
      familiesData = JSON.parse(text);
      return applyChanges(familiesData, approved);
    }).then(function (updatedData) {
      // Write back via File System Access API
      return familiesHandle.createWritable().then(function (writable) {
        return writable.write(JSON.stringify(updatedData, null, 2)).then(function () {
          return writable.close();
        });
      });
    }).then(function () {
      // Mark applied items
      approved.forEach(function (u) { u.status = 'applied'; });
      saveQueue();
      renderQueue();
      addSystemMessage('Successfully applied ' + approved.length + ' changes to families.json.');
    }).catch(function (e) {
      if (e.name !== 'AbortError') {
        alert('Error applying changes: ' + e.message);
        console.error(e);
      }
    });
  }

  function applyWithDownload(approved) {
    // Fallback: load families.json from data/, apply changes, offer download
    fetch('data/families.json').then(function (r) { return r.json(); }).then(function (data) {
      familiesData = data;
      return applyChanges(familiesData, approved);
    }).then(function (updatedData) {
      // Download as file
      var blob = new Blob([JSON.stringify(updatedData, null, 2)], { type: 'application/json' });
      var url = URL.createObjectURL(blob);
      var a = document.createElement('a');
      a.href = url;
      a.download = 'families.json';
      a.click();
      URL.revokeObjectURL(url);

      approved.forEach(function (u) { u.status = 'applied'; });
      saveQueue();
      renderQueue();
      addSystemMessage('Downloaded updated families.json with ' + approved.length + ' changes. Replace the file in data/ manually.');
    }).catch(function (e) {
      alert('Error: ' + e.message);
    });
  }

  function recountSummary(family) {
    var stds = family.standards && family.standards.standards;
    if (!stds || !family.standards.summary) return;
    var hens = 0; var eads = 0;
    stds.forEach(function (s) {
      if (s.type === 'hEN') hens++;
      else if (s.type === 'EAD') eads++;
    });
    family.standards.summary.hen_listed = hens;
    family.standards.summary.ead_listed = eads;
    // Also keep hen_count/ead_count in sync if they match listed (i.e. completeness is full)
    if (family.standards.summary.completeness === 'full') {
      family.standards.summary.hen_count = hens;
      family.standards.summary.ead_count = eads;
    }
  }

  function applyChanges(familiesArr, updates) {
    var errors = [];
    var familiesModified = {};

    updates.forEach(function (update) {
      // Skip no-op confirmations
      if ((update.action || 'set') === 'set' &&
          JSON.stringify(update.current_value) === JSON.stringify(update.proposed_value)) {
        return;
      }

      // Find the family in the array
      var family = familiesArr.find(function (f) {
        return f.letter === update.family;
      });

      if (!family) {
        errors.push(update.id + ': family "' + update.family + '" not found');
        return;
      }

      var action = update.action || 'set';
      var field = update.field;
      var newValue = update.proposed_value;

      if (action === 'update_standard') {
        var stds = family.standards && family.standards.standards;
        if (!stds) { errors.push(update.id + ': no standards array for ' + update.family); return; }
        var target = stds.find(function (s) { return s.id === update.standard_id; });
        if (!target) { errors.push(update.id + ': standard "' + update.standard_id + '" not found in ' + update.family); return; }
        if (typeof newValue === 'object' && newValue !== null) {
          Object.keys(newValue).forEach(function (k) { target[k] = newValue[k]; });
        }

      } else if (action === 'add_standard') {
        if (!family.standards) family.standards = {};
        if (!family.standards.standards) family.standards.standards = [];
        var exists = family.standards.standards.find(function (s) { return s.id === (newValue && newValue.id); });
        if (exists) {
          Object.keys(newValue).forEach(function (k) { exists[k] = newValue[k]; });
        } else {
          family.standards.standards.push(newValue);
        }
        familiesModified[update.family] = family;

      } else if (action === 'remove_standard') {
        var stdsList = family.standards && family.standards.standards;
        if (!stdsList) { errors.push(update.id + ': no standards array for ' + update.family); return; }
        var removeId = update.standard_id;
        var idx = stdsList.findIndex(function (s) { return s.id === removeId; });
        if (idx === -1) { errors.push(update.id + ': standard "' + removeId + '" not found in ' + update.family); return; }
        stdsList.splice(idx, 1);
        familiesModified[update.family] = family;

      } else {
        // Default 'set' action
        if (field.indexOf('.') !== -1) {
          var parts = field.split('.');
          var obj = family;
          for (var i = 0; i < parts.length - 1; i++) {
            if (obj[parts[i]] === undefined) {
              obj[parts[i]] = {};
            }
            obj = obj[parts[i]];
          }
          obj[parts[parts.length - 1]] = newValue;
        } else {
          family[field] = newValue;
        }
      }

      // Update the 'updated' timestamp
      family.updated = new Date().toISOString().split('T')[0];
    });

    // Auto-update standards.summary for families that had standards added/removed
    Object.keys(familiesModified).forEach(function (letter) {
      recountSummary(familiesModified[letter]);
    });

    // Report errors
    if (errors.length > 0) {
      addSystemMessage('Apply warnings (' + errors.length + '): ' + errors.join('; '));
    }

    return familiesArr;
  }

  // ─── Clear Queue ───
  function clearQueue() {
    if (!confirm('Clear all items from the review queue?')) return;
    queue = null;
    localStorage.removeItem(LS_QUEUE_KEY);
    renderQueue();
  }

  // ─── Tabs ───
  function initTabs() {
    var tabs = document.querySelectorAll('.admin-tab');
    tabs.forEach(function (tab) {
      tab.addEventListener('click', function () {
        var target = tab.getAttribute('data-tab');
        tabs.forEach(function (t) { t.classList.remove('admin-tab--active'); });
        tab.classList.add('admin-tab--active');

        document.querySelectorAll('.admin-panel').forEach(function (p) {
          p.classList.remove('admin-panel--active');
        });
        document.getElementById('panel' + capitalize(target)).classList.add('admin-panel--active');
      });
    });
  }

  // ─── Chat ───
  function loadChat() {
    var saved = localStorage.getItem(LS_CHAT_KEY);
    if (saved) {
      try {
        var messages = JSON.parse(saved);
        messages.forEach(function (msg) {
          appendChatMessage(msg.type, msg.text, msg.time, true);
        });
      } catch (e) {
        // ignore
      }
    }
  }

  function saveChat() {
    var msgs = [];
    chatMessages.querySelectorAll('.chat-msg').forEach(function (el) {
      if (el.classList.contains('chat-msg--system') && el.dataset.persisted !== 'true') return;
      msgs.push({
        type: el.classList.contains('chat-msg--user') ? 'user' : (el.classList.contains('chat-msg--agent') ? 'agent' : 'system'),
        text: el.querySelector('.chat-msg__text') ? el.querySelector('.chat-msg__text').textContent : el.textContent.trim(),
        time: el.querySelector('.chat-msg__time') ? el.querySelector('.chat-msg__time').textContent : ''
      });
    });
    localStorage.setItem(LS_CHAT_KEY, JSON.stringify(msgs));
  }

  function sendChat() {
    var text = chatInput.value.trim();
    if (!text) return;

    // Detect if this looks like agent output (starts with ## or contains structured markers)
    var isAgent = text.indexOf('## ') === 0 || text.indexOf('### ') !== -1 || text.indexOf('**') !== -1;
    var type = isAgent ? 'agent' : 'user';

    appendChatMessage(type, text);
    chatInput.value = '';
    chatInput.style.height = 'auto';
    saveChat();
  }

  function addSystemMessage(text) {
    appendChatMessage('system', text, null, false, true);
    saveChat();
  }

  function appendChatMessage(type, text, time, skipScroll, persisted) {
    var msg = document.createElement('div');
    msg.className = 'chat-msg chat-msg--' + type;
    if (persisted) msg.dataset.persisted = 'true';

    var timeStr = time || new Date().toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' });

    msg.innerHTML =
      '<span class="chat-msg__text">' + escapeHtml(text) + '</span>' +
      '<span class="chat-msg__time">' + escapeHtml(timeStr) + '</span>';

    chatMessages.appendChild(msg);
    if (!skipScroll) {
      chatMessages.scrollTop = chatMessages.scrollHeight;
    }
  }

  // ─── Utilities ───
  function escapeHtml(str) {
    if (str === null || str === undefined) return '(empty)';
    if (typeof str !== 'string') str = JSON.stringify(str);
    var div = document.createElement('div');
    div.textContent = str;
    return div.innerHTML;
  }

  function formatValue(val) {
    if (val === null || val === undefined) return '(empty)';
    if (typeof val === 'object') return JSON.stringify(val);
    return String(val);
  }

  function capitalize(str) {
    return str.charAt(0).toUpperCase() + str.slice(1);
  }

  // ─── Auto-resize textarea ───
  function autoResize() {
    chatInput.style.height = 'auto';
    chatInput.style.height = Math.min(chatInput.scrollHeight, 120) + 'px';
  }

  // ─── Init ───
  function init() {
    // Auth
    authBtn.addEventListener('click', authenticate);
    authInput.addEventListener('keydown', function (e) {
      if (e.key === 'Enter') authenticate();
    });

    // Queue loading
    loadQueueBtn.addEventListener('click', loadQueueFromFile);
    loadQueueBtnEmpty.addEventListener('click', loadQueueFromFile);
    applyApprovedBtn.addEventListener('click', applyApproved);
    clearQueueBtn.addEventListener('click', clearQueue);

    // Tabs
    initTabs();

    // Chat
    chatSendBtn.addEventListener('click', sendChat);
    chatInput.addEventListener('keydown', function (e) {
      if (e.key === 'Enter' && !e.shiftKey) {
        e.preventDefault();
        sendChat();
      }
    });
    chatInput.addEventListener('input', autoResize);

    // Check auth
    checkAuth();
  }

  init();
})();
