/**
 * PDF Report Generation using jsPDF — Battery Passport Compliance Report.
 */

const PDFReport = {
  // Brand colors
  EMERALD: [0, 145, 75],
  NAVY: [36, 54, 68],
  NAVY_LIGHT: [87, 129, 161],
  WHITE: [255, 255, 255],
  LIGHT_BG: [248, 249, 250],
  RED: [231, 24, 70],
  ORANGE: [255, 169, 45],
  MEDIUM_GREY: [140, 140, 140],

  async generate(engine) {
    if (!window.jspdf) {
      alert('PDF library is still loading. Please try again in a moment.');
      return;
    }
    try {
      const { jsPDF } = window.jspdf;
      const doc = new jsPDF('p', 'mm', 'a4');
      const pageWidth = doc.internal.pageSize.getWidth();
      const pageHeight = doc.internal.pageSize.getHeight();
      const margin = 18;
      const contentWidth = pageWidth - margin * 2;
      let y = 0;

      const matched = engine.getMatchedRegulations();
      const gate = engine.getGateVerdict();
      const verdict = gate.verdict;
      const profile = engine.getProfileSummary();
      const mandatory = matched.filter(r => r.status !== 'voluntary' && r.status !== 'future');
      const future = matched.filter(r => r.status === 'future');

      // ── Load logo ──────────────────────────────────────────
      let logoData = null;
      try {
        const resp = await fetch('images/logo.png');
        const blob = await resp.blob();
        logoData = await new Promise(resolve => {
          const reader = new FileReader();
          reader.onload = () => resolve(reader.result);
          reader.readAsDataURL(blob);
        });
      } catch (e) {
        console.warn('Could not load logo for PDF:', e);
      }

      // ── Helper functions ─────────────────────────────────────
      const checkPage = (needed) => {
        if (y + needed > pageHeight - 25) {
          doc.addPage();
          y = 20;
        }
      };

      const addFooter = (pageNum, totalPages) => {
        doc.setFontSize(7);
        doc.setTextColor(...this.NAVY_LIGHT);
        doc.text(`Page ${pageNum} of ${totalPages}`, pageWidth / 2, pageHeight - 8, { align: 'center' });
        doc.text('Generated by "Do I Need a Battery Passport?" \u2014 regenstudio.world', pageWidth / 2, pageHeight - 4.5, { align: 'center' });
      };

      const sectionHeading = (title) => {
        checkPage(16);
        doc.setFillColor(...this.EMERALD);
        doc.rect(margin, y, contentWidth, 0.6, 'F');
        y += 4;
        doc.setTextColor(...this.EMERALD);
        doc.setFontSize(13);
        doc.setFont('helvetica', 'bold');
        doc.text(title, margin, y + 4);
        y += 10;
      };

      const label = (text, xPos, yPos) => {
        doc.setFont('helvetica', 'bold');
        doc.setFontSize(8);
        doc.setTextColor(...this.NAVY);
        doc.text(text, xPos, yPos);
      };

      const value = (text, xPos, yPos, maxWidth) => {
        doc.setFont('helvetica', 'normal');
        doc.setFontSize(8);
        doc.setTextColor(...this.NAVY);
        if (maxWidth) {
          const lines = doc.splitTextToSize(text, maxWidth);
          doc.text(lines, xPos, yPos);
          return lines.length;
        }
        doc.text(text, xPos, yPos);
        return 1;
      };

      // ── COVER / HEADER ─────────────────────────────────────
      // White background header with emerald accent bar at top
      doc.setFillColor(...this.EMERALD);
      doc.rect(0, 0, pageWidth, 4, 'F');

      // Logo on white background (logo has dark text that needs light bg)
      if (logoData) {
        doc.addImage(logoData, 'PNG', margin, 8, 50, 13.3);
      }

      // Date + website - right side
      doc.setFontSize(7.5);
      doc.setFont('helvetica', 'normal');
      doc.setTextColor(...this.NAVY_LIGHT);
      doc.text(
        new Date().toLocaleDateString('en-GB', { day: 'numeric', month: 'long', year: 'numeric' }),
        pageWidth - margin, 12, { align: 'right' }
      );
      doc.setTextColor(...this.EMERALD);
      doc.text('regenstudio.world', pageWidth - margin, 17, { align: 'right' });

      // Title below logo
      doc.setTextColor(...this.NAVY);
      doc.setFontSize(20);
      doc.setFont('helvetica', 'bold');
      doc.text('Battery Passport Compliance Report', margin, 32);

      // Subtle separator line
      doc.setDrawColor(...this.EMERALD);
      doc.setLineWidth(0.6);
      doc.line(margin, 36, pageWidth - margin, 36);

      y = 42;

      // ── PROMINENT DISCLAIMER BOX ───────────────────────────
      doc.setFillColor(255, 245, 245);
      doc.setDrawColor(...this.RED);
      doc.setLineWidth(0.5);
      const disclaimerText = 'IMPORTANT DISCLAIMER: This report is generated by a tool in demo mode. ' +
        'The legal and regulatory information presented has NOT been independently verified by legal experts. ' +
        'This document does not constitute legal advice. Companies must not base compliance decisions solely on this report. ' +
        'Always consult qualified legal counsel before making regulatory decisions. ' +
        'Regulatory requirements, deadlines, and interpretations may change.';
      const disclaimerLines = doc.splitTextToSize(disclaimerText, contentWidth - 10);
      const disclaimerHeight = disclaimerLines.length * 3.8 + 10;
      doc.roundedRect(margin, y, contentWidth, disclaimerHeight, 2, 2, 'FD');

      doc.setTextColor(...this.RED);
      doc.setFontSize(8);
      doc.setFont('helvetica', 'bold');
      doc.text('\u26A0  DEMO \u2014 NOT LEGAL ADVICE', margin + 5, y + 5);
      doc.setFont('helvetica', 'normal');
      doc.setFontSize(7.5);
      doc.setTextColor(80, 80, 80);
      doc.text(disclaimerLines, margin + 5, y + 10);
      y += disclaimerHeight + 6;

      // ── EXECUTIVE SUMMARY ──────────────────────────────────
      sectionHeading('Executive Summary');

      // Verdict box
      const verdictTexts = {
        yes: 'YES \u2014 You Need a Battery Passport',
        likely: 'LIKELY \u2014 Battery Passport May Apply',
        no: 'NO \u2014 No Battery Passport Required'
      };
      const verdictColors = {
        yes: this.RED,
        likely: this.ORANGE,
        no: this.EMERALD
      };
      const vc = verdictColors[verdict] || this.ORANGE;

      // Verdict background tint
      doc.setFillColor(
        Math.round(255 - (255 - vc[0]) * 0.08),
        Math.round(255 - (255 - vc[1]) * 0.08),
        Math.round(255 - (255 - vc[2]) * 0.08)
      );
      doc.setDrawColor(...vc);
      doc.setLineWidth(0.4);
      doc.roundedRect(margin, y, contentWidth, 12, 2, 2, 'FD');

      doc.setTextColor(...vc);
      doc.setFontSize(11);
      doc.setFont('helvetica', 'bold');
      doc.text(verdictTexts[verdict] || verdictTexts.likely, margin + 4, y + 8);
      y += 17;

      // Gate verdict reason
      doc.setTextColor(...this.NAVY);
      doc.setFontSize(8);
      doc.setFont('helvetica', 'normal');
      const reasonLines = doc.splitTextToSize(gate.reason, contentWidth);
      reasonLines.forEach(line => {
        checkPage(5);
        doc.text(line, margin, y);
        y += 3.8;
      });
      y += 3;

      if (gate.deadline) {
        checkPage(6);
        doc.setFont('helvetica', 'bold');
        doc.setFontSize(8);
        doc.text('Key Deadline: ' + gate.deadline, margin, y);
        doc.setFont('helvetica', 'normal');
        y += 5;
      }

      doc.setFontSize(8);
      doc.text('Total applicable regulations: ' + mandatory.length + ' mandatory, ' + future.length + ' future', margin, y);
      y += 4;

      const nearest = engine.getNearestDeadline();
      if (nearest) {
        doc.text('Nearest deadline: ' + nearest.timeline.label + ' (' + nearest.name + ')', margin, y);
        y += 4;
      }
      y += 6;

      // ── YOUR ANSWERS (SUMMARY) ─────────────────────────────
      sectionHeading('Your Answers');

      const allQuestions = [...GATE_QUESTIONS, ...DEEP_DIVE_QUESTIONS];
      const answeredQuestions = allQuestions.filter(q => {
        const ans = engine.getAnswer(q.id);
        return ans !== null && ans !== undefined && (!Array.isArray(ans) || ans.length > 0);
      });

      // Two-column layout for answers
      const colWidth = (contentWidth - 4) / 2;
      const colX = [margin, margin + colWidth + 4];
      let col = 0;
      let colY = [y, y];

      answeredQuestions.forEach(q => {
        const ans = engine.getAnswer(q.id);
        let answerText;
        if (Array.isArray(ans)) {
          answerText = ans.map(a => {
            const opt = q.options.find(o => o.id === a);
            return opt ? opt.label : a;
          }).join(', ');
        } else {
          const opt = q.options.find(o => o.id === ans);
          answerText = opt ? opt.label : ans;
        }

        // Shortened question text
        const shortQ = q.question.replace(/\?$/, '').replace(/^Do you |^Are you |^Have you |^What is |^What |^Which |^When |^Where |^How /i, '');
        const qLabel = shortQ.charAt(0).toUpperCase() + shortQ.slice(1);

        // Check if we need a new page for this column
        const neededHeight = 10;
        if (colY[col] + neededHeight > pageHeight - 30) {
          // If both columns full, new page
          if (col === 1 || colY[0] + neededHeight > pageHeight - 30) {
            doc.addPage();
            colY = [20, 20];
            col = 0;
          }
        }

        const cx = colX[col];
        const cy = colY[col];

        doc.setFillColor(...this.LIGHT_BG);
        doc.roundedRect(cx, cy, colWidth, 9, 1, 1, 'F');

        doc.setFont('helvetica', 'bold');
        doc.setFontSize(6.5);
        doc.setTextColor(...this.NAVY_LIGHT);
        const truncQ = qLabel.length > 48 ? qLabel.substring(0, 46) + '\u2026' : qLabel;
        doc.text(truncQ, cx + 2, cy + 3.5);

        doc.setFont('helvetica', 'normal');
        doc.setFontSize(7.5);
        doc.setTextColor(...this.NAVY);
        const truncA = answerText.length > 48 ? answerText.substring(0, 46) + '\u2026' : answerText;
        doc.text(truncA, cx + 2, cy + 7.5);

        colY[col] += 11;
        col = col === 0 ? 1 : 0;
      });

      y = Math.max(colY[0], colY[1]) + 4;

      // ── COMPANY PROFILE ────────────────────────────────────
      checkPage(40);
      sectionHeading('Company Profile');

      const profileItems = [
        ['Headquarters', profile.headquarters],
        ['Supply Chain Role', profile.role],
        ['Company Size', profile.companySize],
        ['Employee Count', profile.employeeCount],
        ['Annual Turnover', profile.annualTurnover],
        ['EU Market', profile.euMarket],
        ['B2C Sales', profile.b2cSales],
        ['Battery Types', profile.batteryTypes],
        ['Battery Capacity', profile.batteryCapacity],
        ['Rechargeable', profile.rechargeable],
        ['Market Timing', profile.marketTiming],
        ['Traceability', profile.traceability],
        ['Carbon Footprint Tracking', profile.carbonFootprint],
        ['REACH/SCIP Compliance', profile.substances],
        ['Battery Passport Status', profile.dppStatus]
      ].filter(([, v]) => v);

      // Profile as two-column key-value
      const profColWidth = (contentWidth - 4) / 2;
      const profColX = [margin, margin + profColWidth + 4];
      let profCol = 0;
      let profColY = [y, y];

      profileItems.forEach(([lbl, val]) => {
        const cx = profColX[profCol];
        const cy = profColY[profCol];

        if (cy + 6 > pageHeight - 25) {
          doc.addPage();
          profColY = [20, 20];
          profCol = 0;
        }

        doc.setFont('helvetica', 'bold');
        doc.setFontSize(7.5);
        doc.setTextColor(...this.NAVY);
        doc.text(lbl + ':', cx, profColY[profCol]);

        doc.setFont('helvetica', 'normal');
        const lblW = doc.getTextWidth(lbl + ':  ');
        const truncVal = val.length > 35 ? val.substring(0, 33) + '\u2026' : val;
        doc.text(truncVal, cx + lblW, profColY[profCol]);

        profColY[profCol] += 5;
        profCol = profCol === 0 ? 1 : 0;
      });

      y = Math.max(profColY[0], profColY[1]) + 6;

      // ── REGULATORY REQUIREMENTS TABLE ──────────────────────
      checkPage(20);
      sectionHeading('Regulatory Requirements');

      // Helper: truncate text to fit a max width in mm using actual font metrics
      const fitText = (text, maxW) => {
        if (!text) return '';
        if (doc.getTextWidth(text) <= maxW) return text;
        let t = text;
        while (t.length > 1 && doc.getTextWidth(t + '\u2026') > maxW) {
          t = t.slice(0, -1);
        }
        return t + '\u2026';
      };

      // Column positions relative to margin (total contentWidth = 174mm)
      const col1X = margin + 2;        // Requirement
      const col2X = margin + 62;       // Regulation
      const col3X = margin + 110;      // Deadline
      const col4X = margin + 148;      // Urgency
      const col1W = 58;                // Requirement width
      const col2W = 46;                // Regulation width
      const col3W = 36;                // Deadline width
      const col4W = contentWidth - 150; // Urgency width

      if (mandatory.length > 0) {
        // Table header
        doc.setFillColor(...this.NAVY);
        doc.rect(margin, y, contentWidth, 7, 'F');
        doc.setTextColor(...this.WHITE);
        doc.setFontSize(6.5);
        doc.setFont('helvetica', 'bold');
        doc.text('Requirement', col1X, y + 4.5);
        doc.text('Regulation', col2X, y + 4.5);
        doc.text('Deadline', col3X, y + 4.5);
        doc.text('Urgency', col4X, y + 4.5);
        y += 7;

        mandatory.forEach((reg, i) => {
          checkPage(8);
          if (i % 2 === 0) {
            doc.setFillColor(...this.LIGHT_BG);
            doc.rect(margin, y, contentWidth, 7, 'F');
          }

          doc.setTextColor(...this.NAVY);
          doc.setFontSize(6.5);
          doc.setFont('helvetica', 'normal');

          doc.text(fitText(reg.name, col1W), col1X, y + 4.5);
          doc.text(fitText(reg.regulation, col2W), col2X, y + 4.5);
          doc.text(fitText(reg.timeline.label || 'TBD', col3W), col3X, y + 4.5);

          const urgColors = { critical: this.RED, high: this.ORANGE, medium: this.NAVY_LIGHT, low: [180, 180, 180] };
          const uc = urgColors[reg.urgencyLevel] || this.NAVY_LIGHT;
          doc.setFillColor(...uc);
          doc.circle(col4X + 2, y + 3.5, 1.2, 'F');

          const urgLabels = { critical: 'Critical', high: 'High', medium: 'Medium', low: 'Low' };
          doc.text(urgLabels[reg.urgencyLevel] || '', col4X + 5, y + 4.5);

          y += 7;
        });
      } else {
        doc.setTextColor(...this.NAVY);
        doc.setFontSize(8);
        doc.text('No mandatory regulations currently apply to your profile.', margin, y);
        y += 6;
      }
      y += 4;

      // ── FUTURE REQUIREMENTS ────────────────────────────────
      if (future.length > 0) {
        checkPage(16);
        sectionHeading('Future Requirements to Monitor');

        future.forEach(reg => {
          checkPage(8);
          doc.setTextColor(...this.NAVY);
          doc.setFontSize(7.5);
          doc.setFont('helvetica', 'bold');
          doc.text('\u2022 ' + reg.name, margin, y);
          doc.setFont('helvetica', 'normal');
          doc.setFontSize(7);
          doc.text('  Expected: ' + reg.timeline.label, margin + 3, y + 4);
          y += 9;
        });
        y += 2;
      }

      // ── COMPLIANCE TIMELINE ────────────────────────────────
      const withDates = matched.filter(r => r.timeline.date && r.status !== 'voluntary')
        .sort((a, b) => new Date(a.timeline.date) - new Date(b.timeline.date));

      if (withDates.length > 0) {
        checkPage(24);
        sectionHeading('Compliance Timeline');

        withDates.forEach(reg => {
          checkPage(6);
          const isPast = new Date(reg.timeline.date) < new Date();
          const uc = isPast ? this.RED : (reg.urgencyLevel === 'high' ? this.ORANGE : this.EMERALD);
          doc.setFillColor(...uc);
          doc.circle(margin + 2, y - 0.5, 1.5, 'F');

          doc.setTextColor(...this.NAVY);
          doc.setFontSize(7);
          doc.setFont('helvetica', 'bold');
          const dateLabel = fitText(reg.timeline.label, 45);
          doc.text(dateLabel, margin + 6, y);

          doc.setFont('helvetica', 'normal');
          const dateLabelW = doc.getTextWidth(dateLabel + '  ');
          const inEffectW = isPast ? 18 : 0; // reserve space for "IN EFFECT" label
          const remainingWidth = contentWidth - 6 - dateLabelW - inEffectW;
          const regNameText = '\u2014 ' + reg.name;
          doc.text(fitText(regNameText, remainingWidth), margin + 6 + dateLabelW, y);

          if (isPast) {
            doc.setTextColor(...this.RED);
            doc.setFontSize(6);
            doc.text('IN EFFECT', pageWidth - margin, y, { align: 'right' });
          }
          y += 5;
        });
        y += 4;
      }

      // ── NEXT STEPS ───────────────────────────────────────────
      const steps = this._getNextSteps(engine, matched);
      if (steps.length > 0) {
        checkPage(20);
        sectionHeading('Recommended Next Steps');

        const priorityLabels = {
          critical: 'Critical',
          urgent: 'Urgent',
          high: 'High Priority',
          medium: 'Recommended',
          low: 'Good to Know',
          info: 'Get Help'
        };
        const priorityColors = {
          critical: this.RED,
          urgent: this.RED,
          high: this.ORANGE,
          medium: this.NAVY_LIGHT,
          low: [180, 180, 180],
          info: this.EMERALD
        };

        steps.forEach((step, i) => {
          const descLines = doc.splitTextToSize(step.description, contentWidth - 12);
          const stepHeight = 6 + descLines.length * 3.2 + 3;
          checkPage(stepHeight);

          // Priority badge
          const pc = priorityColors[step.priority] || this.NAVY_LIGHT;
          doc.setFillColor(
            Math.round(255 - (255 - pc[0]) * 0.08),
            Math.round(255 - (255 - pc[1]) * 0.08),
            Math.round(255 - (255 - pc[2]) * 0.08)
          );
          doc.rect(margin, y, contentWidth, stepHeight, 'F');
          doc.setFillColor(...pc);
          doc.rect(margin, y, 1.2, stepHeight, 'F');

          // Step number + title
          doc.setTextColor(...this.NAVY);
          doc.setFontSize(7.5);
          doc.setFont('helvetica', 'bold');
          doc.text((i + 1) + '. ' + step.title, margin + 4, y + 4.5);

          // Priority label
          doc.setFontSize(6);
          doc.setTextColor(...pc);
          doc.text(priorityLabels[step.priority] || '', pageWidth - margin - 2, y + 4.5, { align: 'right' });

          // Description
          doc.setTextColor(80, 80, 80);
          doc.setFontSize(6.5);
          doc.setFont('helvetica', 'normal');
          doc.text(descLines, margin + 4, y + 8.5);

          y += stepHeight + 2;
        });
        y += 2;
      }

      // ── FINAL DISCLAIMER ───────────────────────────────────
      checkPage(30);
      doc.setDrawColor(...this.NAVY_LIGHT);
      doc.line(margin, y, pageWidth - margin, y);
      y += 5;

      // Repeat prominent disclaimer at the bottom
      doc.setFillColor(255, 245, 245);
      doc.setDrawColor(...this.RED);
      doc.setLineWidth(0.4);
      const finalDisclaimer = 'DISCLAIMER \u2014 DEMO MODE: This report has been generated by an automated assessment tool that is currently in demo mode. ' +
        'The legal and regulatory information contained herein has NOT been independently verified by qualified legal experts. ' +
        'This document does NOT constitute legal advice and should NOT be relied upon as the sole basis for any compliance decision. ' +
        'Companies are strongly advised to consult with qualified legal counsel specialising in EU product compliance and battery regulation before taking action. ' +
        'Regulatory requirements, deadlines, interpretations, and enforcement practices may change. ' +
        'Regen Studio accepts no liability for decisions made based on this report.';
      const finalLines = doc.splitTextToSize(finalDisclaimer, contentWidth - 10);
      const finalHeight = finalLines.length * 3.5 + 8;
      doc.roundedRect(margin, y, contentWidth, finalHeight, 2, 2, 'FD');

      doc.setTextColor(...this.RED);
      doc.setFontSize(7);
      doc.setFont('helvetica', 'bold');
      doc.text('\u26A0  NOT LEGAL ADVICE \u2014 DEMO MODE', margin + 5, y + 5);
      doc.setFont('helvetica', 'italic');
      doc.setFontSize(6.5);
      doc.setTextColor(80, 80, 80);
      doc.text(finalLines, margin + 5, y + 9);
      y += finalHeight + 5;

      // Regen Studio sign-off
      checkPage(10);
      if (logoData) {
        doc.addImage(logoData, 'PNG', margin, y, 30, 8);
        doc.setTextColor(...this.NAVY);
        doc.setFontSize(7);
        doc.setFont('helvetica', 'normal');
        doc.text('regenstudio.world', margin + 32, y + 5);
      } else {
        doc.setTextColor(...this.EMERALD);
        doc.setFontSize(9);
        doc.setFont('helvetica', 'bold');
        doc.text('Regen Studio \u2014 regenstudio.world', margin, y + 5);
      }

      // ── Add footers to all pages ───────────────────────────
      const totalPages = doc.internal.getNumberOfPages();
      for (let i = 1; i <= totalPages; i++) {
        doc.setPage(i);
        addFooter(i, totalPages);
      }

      // ── Download ───────────────────────────────────────────
      doc.save('demo-battery-passport-compliance-report-by-regen-studio.pdf');
    } catch (err) {
      console.error('PDF generation failed:', err);
      alert('Failed to generate PDF. Please try again or contact support.');
    }
  },

  /**
   * Build the Next Steps array — mirrors the logic in Results.renderNextSteps.
   */
  _getNextSteps(engine, matched) {
    const steps = [];
    const gate = engine.getGateVerdict();
    const verdict = gate.verdict;
    const hasActive = matched.some(r => r.status === 'active');
    const hasUpcoming = matched.some(r => r.status === 'upcoming');
    const role = engine.getRole();

    const dppStatus = engine.getAnswer('q_dpp_status');
    const cfStatus = engine.getAnswer('q_carbon_footprint');
    const traceability = engine.getAnswer('q_traceability');
    const substancesStatus = engine.getAnswer('q_substances');
    const headquarters = engine.getAnswer('q_headquarters');

    if (hasActive) {
      steps.push({ priority: 'urgent', title: 'Address active requirements immediately', description: 'Some Battery Regulation requirements that apply to your batteries are already in effect. Review the Requirements section for details and take action to ensure compliance.' });
      steps.push({ priority: 'urgent', title: 'Prepare for market surveillance inspections', description: 'Active regulations mean market surveillance authorities can already inspect your batteries. Ensure you can present your EU Declaration of Conformity, technical documentation, and CE marking evidence on request.' });
    }

    const isNonEU = headquarters === 'outside_europe' || headquarters === 'uk';
    if (isNonEU && engine.isEUMarket() && (role === 'manufacturer' || role === 'importer')) {
      steps.push({ priority: 'critical', title: 'Designate an EU authorised representative', description: 'As a non-EU manufacturer placing batteries on the EU market, Regulation (EU) 2019/1020 Article 4 requires an EU-established responsible person who must keep your Declaration of Conformity and technical documentation available to authorities.' });
    }

    if (dppStatus === 'not_aware' || dppStatus === 'aware') {
      steps.push({ priority: 'high', title: 'Begin Digital Battery Passport planning', description: 'The Battery Passport deadline is February 2027 (EV/industrial) and August 2027 (LMT). Start by mapping the ~80 required data attributes (Annex XIII) against your current data availability.' });
    }

    if (cfStatus === 'no' || cfStatus === 'planning') {
      steps.push({ priority: 'high', title: 'Start carbon footprint tracking', description: 'Carbon footprint declarations are required for EV, industrial (\u22652 kWh), and LMT batteries using the Product Environmental Footprint (PEF) methodology. Begin lifecycle assessment work now.' });
    }

    if (traceability === 'none' || traceability === 'dont_know') {
      steps.push({ priority: 'high', title: 'Implement supply chain traceability', description: 'Battery Regulation due diligence requirements (effective August 2027) require supply chain mapping for cobalt, lithium, nickel, and natural graphite. Build traceability systems now.' });
    }

    if (substancesStatus === 'no' || substancesStatus === 'partial') {
      steps.push({ priority: 'high', title: 'Prepare substance of concern tracking', description: 'Battery Regulation and REACH require tracking and declaring substances of concern including SVHCs. Map all hazardous substances in your batteries, including concentration and component location.' });
    }

    const svhcPresence = engine.getAnswer('q_svhc_presence');
    if (svhcPresence === 'yes_known' || svhcPresence === 'possibly') {
      steps.push({ priority: 'high', title: 'Screen for SVHCs and complete SCIP database notifications', description: 'Your answers indicate SVHCs may be present in your batteries. Conduct a Candidate List screening and submit SCIP notifications to ECHA for articles containing SVHCs above 0.1% w/w.' });
    }

    const conformityAssessment = engine.getAnswer('q_conformity_assessment');
    if ((role === 'manufacturer' || role === 'importer') && (hasActive || hasUpcoming) && (conformityAssessment === 'none' || conformityAssessment === 'not_sure')) {
      steps.push({ priority: 'high', title: 'Verify CE marking and EU Declaration of Conformity', description: 'For every battery you place on the EU market under harmonised legislation, you must affix the CE marking and prepare an EU Declaration of Conformity. Keep technical documentation available for at least 10 years.' });
    }

    const eprRegistration = engine.getAnswer('q_epr_registration');
    if ((role === 'manufacturer' || role === 'importer') && (eprRegistration === 'no' || eprRegistration === 'not_sure')) {
      steps.push({ priority: 'high', title: 'Register with battery EPR schemes', description: 'Battery producers and importers placing batteries on the EU market must register with Extended Producer Responsibility schemes in each member state.' });
    }

    steps.push({ priority: 'medium', title: 'Evaluate Battery Passport solution providers', description: 'Consider technology solutions for creating and managing Digital Battery Passports, including QR code generation, data hosting, and access management.' });
    steps.push({ priority: 'medium', title: 'Stay informed on delegated acts', description: 'The European Commission is still publishing delegated acts that specify detailed requirements for battery passports. Monitor EUR-Lex and industry associations for updates.' });

    if (verdict === 'no') {
      steps.push({ priority: 'low', title: 'Monitor Battery Regulation developments', description: 'Even if no Battery Passport requirements apply today, the EU Battery Regulation includes obligations for all battery types (labelling, collection, recycling). Stay informed about evolving requirements.' });
    }

    steps.push({ priority: 'info', title: 'Get expert guidance', description: 'Regen Studio helps companies navigate Battery Passport compliance with tailored strategies, technology selection, and implementation support. Contact us at regenstudio.world.' });

    return steps;
  }
};
